### ISSUE TITLE
Need to update Retry version -- linear backoff is exponential in the current one

### ISSUE THREAD

**Issue by DarkMarmot** [jvoegele/external_service#3]
As with the title, the Retry library did not properly implement linear backoff.
It should be fixed by updating to the latest release. Thanks!

**Comment by jvoegele** [comment]
Hi @DarkMarmot , thanks for reporting. I'll look into updating the `retry` library to the latest version.

There are some backwards-incompatible changes in recent versions that make this somewhat non-trivial, so I'll need to make some changes to the way that `external_service` uses `retry`.

**Comment by jvoegele** [comment]
I have upgraded `retry` to version 0.11.2 and published a new `0.9.0` version of `external_service` to hex.pm.
