### ISSUE TITLE
Allow any term as fuse name

### ISSUE THREAD

**Issue by hexedpackets** [jvoegele/external_service#8]
Fuse v2.4.3 and above [removed the atom-only limitation](https://github.com/jlouis/fuse/commit/a63f068b34f1d4be3d968f0977a1448a6d081ce4) for fuse names. Any chance of also allowing any term for fuses created through external_service? G

lancing through the code I think that removing the guard clauses and bumping the version requirement of fuse would be all that is needed.

**Comment by jvoegele** [comment]
That should be a simple fix. I'll try to get a new release out by this weekend.

**Comment by jvoegele** [comment]
Merged #10 and released as version 1.1.1: https://hex.pm/packages/external_service/1.1.1

**Comment by folcoz** [comment]
I think this issue is not fully closed yet, as ExternalService.stop(non_atom_term) will raise a FunctionClauseError. I guess line 145 in lib/external_service.ex should have "when is_atom(fuse_name)" removed.
Thank you for this useful library!
